version: '3.8'

services:
  calorie_bot:
    build: .
    container_name: calorie_bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/calorie_db
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16
    container_name: calorie_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calorie_db
    ports:
      - "5433:5432"
    volumes:
      - calorie_data:/var/lib/postgresql/data
    restart: always

volumes:
  calorie_data:
