name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout, build и push образ
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/tiimgll/maincalories-docker:latest .
      - run: docker push ghcr.io/tiimgll/maincalories-docker:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > ${{ secrets.SERVER_DIR }}/.env
            docker-compose -f ${{ secrets.SERVER_DIR }}/compose.yml pull
            docker-compose -f ${{ secrets.SERVER_DIR }}/compose.yml down
            docker-compose -f ${{ secrets.SERVER_DIR }}/compose.yml up -d
