name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > ${{ secrets.SERVER_DIR }}/.env
            docker-compose -f ${{ secrets.SERVER_DIR }}/compose.yml pull
            docker-compose -f ${{ secrets.SERVER_DIR }}/compose.yml down
            docker-compose -f ${{ secrets.SERVER_DIR }}/compose.yml up -d
